### ISSUE TITLE
how top change upload size on docker container

### ISSUE THREAD

**Issue by inmanturbo** [codeskyblue/gohttpserver#103]
how to change upload size on docker container?

**Comment by inmanturbo** [comment]
Nevermind. this is error 2021/01/22 16:24:34 httpstaticserver.go:239: Move /tmp/multipart-064775152 -> /app/public/alpine-standard-3.12.3-x86_64.iso
2021/01/22 16:24:34 httpstaticserver.go:252: Handle upload file: <nil>
2021/01/22 16:24:34 server.go:3085: http: panic serving 192.168.30.171:44690: runtime error: invalid memory address or nil pointer dereference
goroutine 15 [running]:
net/http.(*conn).serve.func1(0xc000134d20)
	/usr/local/go/src/net/http/server.go:1795 +0x139
panic(0x933ee0, 0xe2afd0)
	/usr/local/go/src/runtime/panic.go:679 +0x1b2
main.(*HTTPStaticServer).hUploadOrMkdir(0xc0000d45a0, 0xa96a40, 0xc00008c370, 0xc0000d3200)
	/app/gohttpserver/httpstaticserver.go:253 +0x680
net/http.HandlerFunc.ServeHTTP(0xc0000f0fe0, 0xa96a40, 0xc00008c370, 0xc0000d3200)
	/usr/local/go/src/net/http/server.go:2036 +0x44
github.com/gorilla/mux.(*Router).ServeHTTP(0xc0000b9ea0, 0xa96a40, 0xc00008c370, 0xc0000d3200)
	/go/pkg/mod/github.com/gorilla/mux@v1.6.2/mux.go:162 +0x104
main.(*HTTPStaticServer).ServeHTTP(0xc0000d45a0, 0xa96a40, 0xc00008c370, 0xc0000d3000)
	/app/gohttpserver/httpstaticserver.go:97 +0x50
github.com/codeskyblue/go-accesslog.(*LoggingHandler).ServeHTTP(0xc0000ed890, 0xa97140, 0xc0001361c0, 0xc0000d3000)
	/go/pkg/mod/github.com/codeskyblue/go-accesslog@v0.0.0-20171215023101-6188d3bd9371/accesslog.go:162 +0x3cf
net/http.(*ServeMux).ServeHTTP(0xe3d320, 0xa97140, 0xc0001361c0, 0xc0000d3000)
	/usr/local/go/src/net/http/server.go:2416 +0x1bd
net/http.serverHandler.ServeHTTP(0xc0001362a0, 0xa97140, 0xc0001361c0, 0xc0000d3000)
	/usr/local/go/src/net/http/server.go:2831 +0xa4
net/http.(*conn).serve(0xc000134d20, 0xa98600, 0xc0000f2f00)
	/usr/local/go/src/net/http/server.go:1919 +0x875
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:2957 +0x384
