### ISSUE TITLE
請問如何與 supervisor 整合？

### ISSUE THREAD

**Issue by changchichung** [codeskyblue/gohttpserver#36]
感謝您提供的這個程式，非常簡單好用
不過我在嘗試著用  supervisor去啟動這個程式發生問題
```
2018/10/18 08:25:25 httpstaticserver.go:111: GET  /home/neonexus/center_yaml
2018/10/18 08:25:25 httpstaticserver.go:749: Hot load index.html
2018/10/18 08:25:25 server.go:2923: http: panic serving 192.168.11.34:43870: open assets/index.html: no such file or directory
goroutine 76 [running]:
net/http.(*conn).serve.func1(0xc420348280)
	/usr/lib/go-1.10/src/net/http/server.go:1726 +0xd0
panic(0x8b0e20, 0xc4204513e0)
	/usr/lib/go-1.10/src/runtime/panic.go:502 +0x229
```
我用底下的指令，在console下啟動沒有問題，可是丟到 supervisor 啟動就會發生上面的錯誤，找不到 assets 底下的內容？
```
/usr/local/bin/gohttpserver -r /home/neo/center_yaml/ --port 5000 --upload --delete --debug  --auth-type http --auth-http abc:abc123
```

**Comment by hoogw** [comment]
I make it works, this is unix problem, not this project's issue.
